[package]
name = "pixel-contrib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rasterizer = { path = "../rasterizer" }
log = "0.4"
anyhow = "1.0"
nalgebra-glm = "0.18"
clap = { version = "4.4", features = ["derive"] }
simple-logging = "2.0"
rand = "0.8"
rand_chacha = "0.3"
