[workspace]
resolver = "2"

members = [
    "math",
    "rasterizer",
    "pixel-contrib",
    "pixel-contrib-cli",
    "render-lib",
    "viewer",
]

[profile.release-with-debug]
inherits = "release"
debug = true
