[package]
name = "pixel-contrib-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math = { path = "../math" }
quick-error = "2.0"
nalgebra-glm = "0.18"
byteorder = "1"
